/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4hqBF4ZwQDe
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"

export function Component() {
  const [currentIndex, setCurrentIndex] = useState(0)
  const [visitedIndexes, setVisitedIndexes] = useState<number[]>([]);
  const attractions = [
    "富士山 (静岡県)",
    "金閣寺 (京都府)",
    "宮島 (広島県)",
    "奈良公園 (奈良県)",
    "姫路城 (兵庫県)",
    "白川郷 (岐阜県)",
    "屋久島 (鹿児島県)",
    "小樽運河 (北海道)",
    "熊本城 (熊本県)",
    "石垣島 (沖縄県)",
  ]
  const handleNext = () => {
    let nextIndex
    do {
      nextIndex = Math.floor(Math.random() * attractions.length)
    } while (visitedIndexes.includes(nextIndex))
      setCurrentIndex(nextIndex)
      setVisitedIndexes((prev) => [...prev, nextIndex])
  }
  const handlePrev = () => {
    if (currentIndex > 0) {
      setCurrentIndex(currentIndex - 1)
    }
  }
  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <div className="text-4xl font-bold mb-8">{attractions[currentIndex]}</div>
      <div className="flex gap-4">
        <Button onClick={handlePrev}>前へ</Button>
        <Button onClick={handleNext}>次へ</Button>
      </div>
    </div>
  )
}
